### ISSUE TITLE
The number pattern problem is missing

### ISSUE THREAD

**Issue by jishnusaurav** [Ishita-0112/GFG_LC_101#2]

**Comment by rahullli** [comment]
I would like to work on this issue .
Can you please tell more about which number pattern is required ?

**Comment by Ishita-0112** [comment]
@rahulll  Problem for printing unique number patterns is encouraged, if you can find out one feel free to send PR.

**Comment by Ishita-0112** [comment]
> 
> 
> I would like to work on this issue .
> Can you please tell more about which number pattern is required ?
Problem for printing unique number patterns is encouraged, if you can find out one feel free to send PR.
