### ISSUE TITLE
Word Break

### ISSUE THREAD

**Issue by Ishita-0112** [Ishita-0112/GFG_LC_101#20]
Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.

Note that the same word in the dictionary may be reused multiple times in the segmentation.

**Comment by void-57** [comment]
Hey @Ishita-0112 I want to work on it but can you explain more

**Comment by Ishita-0112** [comment]
> Hey @Ishita-0112 I want to work on it but can you explain more

Consider the following dictionary 
```
{ i, like, sam, sung, samsung, mobile, ice, 
  cream, icecream, man, go, mango}
```

Input:  ilike
Output: Yes 
The string can be segmented as "i like".

Input:  ilikesamsung
Output: Yes
The string can be segmented as "i like samsung" 
or "i like sam sung".

**Comment by sayakbanerjee1999** [comment]
I want to work on this issue! Can you please assign this issue to me.
