### ISSUE TITLE
Maximum Consecutive Ones

### ISSUE THREAD

**Issue by Ishita-0112** [Ishita-0112/GFG_LC_101#23]
Given a binary array nums, return the maximum number of consecutive 1's in the array.

Example 1:

Input: nums = [1,1,0,1,1,1]
Output: 3
Explanation: The first two digits or the last three digits are consecutive 1s. The maximum number of consecutive 1s is 3.
Example 2:

Input: nums = [1,0,1,1,0,1]
Output: 2
 

Constraints:

1 <= nums.length <= 105
nums[i] is either 0 or 1.

**Comment by sayakbanerjee1999** [comment]
I want to work on this issue! Can you please assign this issue to me.
